name: Release Major Version

on:
  workflow_call:
    inputs:
      bump_readme:
        required: false
        type: boolean
        default: true
        description: 'Set to false to skip stepping the version in README.md.'
      lein_compile_profile:
        required: false
        type: string
        default: ''
        description: 'Optional Leiningen profile to use (e.g., "dev", "prod", "test").'

    secrets:
      GPG_SIGNING_KEY:
        required: true
        description: 'GPG signing key for signing artifacts.'
      CLOJARS_USER:
        required: true
        description: 'Clojars username for deployment.'
      CLOJARS_PASS:
        required: true
        description: 'Clojars password/token for deployment.'

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Prepare java
        uses: actions/setup-java@v4
        with:
          distribution: adopt
          java-version: 21
      - name: Install clojure tools
        uses: DeLaGuardo/setup-clojure@13.4
        with:
          lein: latest
      - name: compile project
        run: |
          if [ -z "${{ inputs.lein_compile_profile }}" ]; then
            lein compile
          else
            lein with-profile ${{ inputs.lein_compile_profile }} compile
          fi
      - name: test projects
        run: lein test
      - name: Configure GPG key
        env:
          GPG_SIGNING_KEY: ${{ secrets.GPG_SIGNING_KEY }}
        run: echo -n "$GPG_SIGNING_KEY" | base64 --decode | gpg --import >/dev/null 2>/dev/null
      - name: Step major version for release
        run: lein bump major
      - name: Step version in README.md
        if: ${{ inputs.bump_readme == true }}
        run: lein bump-md
      - name: push
        uses: stefanzweifel/git-auto-commit-action@v6
        with:
          commit_message: Stepping project version to prepare it for release
      - name: Deploy to clojars
        env:
          CLOJARS_USER: ${{ secrets.CLOJARS_USER }}
          CLOJARS_PASS: ${{ secrets.CLOJARS_PASS }}
        run: lein deploy clojars
      - name: Bump project version to snapshot
        run: lein bump dev
      - name: push
        uses: stefanzweifel/git-auto-commit-action@v6
        with:
          commit_message: Stepping project version for the next development cycle